[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
target-version = "py39"
select = ["E", "F", "W", "I"]
ignore = []
exclude = [".venv", "venv", "htmlcov"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]