# Generated by Django 5.2.1 on 2025-05-28 15:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("language", models.CharField(default="el", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_javascript", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "news_sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=500, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("author", models.CharField(blank=True, max_length=255)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("language", models.CharField(default="el", max_length=10)),
                ("word_count", models.IntegerField(default=0)),
                ("reading_time", models.IntegerField(default=0)),
                ("is_processed", models.BooleanField(default=False)),
                ("is_enriched", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="news_aggregator.newssource",
                    ),
                ),
            ],
            options={
                "db_table": "articles",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("job_type", models.CharField(max_length=50)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="news_aggregator.article",
                    ),
                ),
            ],
            options={
                "db_table": "processing_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("jargon", "Jargon Analysis"),
                            ("viewpoints", "Viewpoints Analysis"),
                            ("fact_check", "Fact Check"),
                            ("bias", "Bias Analysis"),
                            ("timeline", "Timeline Analysis"),
                            ("expert", "Expert Opinions"),
                            ("x_pulse", "X Pulse Analysis"),
                        ],
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField()),
                ("model_used", models.CharField(default="grok-3", max_length=50)),
                ("processing_time", models.FloatField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="news_aggregator.article",
                    ),
                ),
            ],
            options={
                "db_table": "ai_analyses",
                "indexes": [
                    models.Index(
                        fields=["analysis_type"], name="ai_analyses_analysi_d8401f_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_analyses_created_0be874_idx"
                    ),
                ],
                "unique_together": {("article", "analysis_type")},
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["url"], name="articles_url_426d50_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["published_at"], name="articles_publish_73ad5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_processed", "is_enriched"],
                name="articles_is_proc_77fc7a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(fields=["status"], name="processing__status_96bb49_idx"),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["celery_task_id"], name="processing__celery__4245d2_idx"
            ),
        ),
    ]
